# Introduction to data.table

## Installation

```{r install, eval=FALSE}
install.packages("data.table")
```

```{r load}
library(data.table)
```

## Read in a file

`data.table` can read in files more efficiently thatn the standard functions in R, including `read.csv`, `read.table`, or `scan`. Let's take a look at the function `fread`. 

```{r fread}
df <- data.frame(a = 1:10^4, b = 1:10^4)
write.table(df, file="test.csv", sep=",", row.names=FALSE)
fread("test.csv")

system.time( read.csv("test.csv") )
system.time( fread("test.csv") )
identical(data.frame(fread("test.csv")), read.csv("test.csv"))
```

## Combine data.frames

```{r rbindlist}
df1 <- data.frame(a = 1:4, b = letters[1:4])
df2 <- data.frame(a = 5:8, b = letters[5:8])
l <- list(df1, df2)
rbindlist(l)
do.call(rbind, l)
```

This is much faster than `rbind`

```{r}
df3 <- data.frame(a = 1:10^7, b = 1:10^7)
df4 <- data.frame(a = 1:10^7, b = 1:10^7)
l <- list(df3, df4)
system.time( do.call(rbind, l) )
system.time( rbindlist(l) )
```

## Fast manipulation

```{r}
DT <- data.table(x = rep(letters, 3847), v = rnorm(100022)) 
DT[,sum(v)]
DT[,sum(v),by=x]

system.time( replicate(10, tapply(DT$v,DT$x,sum)) )
system.time( replicate(10, DT[,sum(v),by=x]) )
```